language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

cache:
  directories:
    - $HOME/.gradle

before_install:
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo "bintray.user=user" >> local.properties
  - echo "bintray.apikey=key" >> local.properties
script:
  - ./gradlew clean assemble test
